name: Publish TechDocs Site

on:
  push:
    branches: [main]
    paths:
    - "catalog/**"
jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest

    env:
      TECHDOCS_S3_BUCKET_NAME: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      ENTITY_NAMESPACE: 'default'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install yq
        run: sudo snap install yq

      - name: Install techdocs-cli
        run: npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Generate and publish docs
        run: |
          cd catalog
          for f in $(find . -name 'mkdocs.yml'); do 
            file_dir=$(dirname $f)
            catalog_file=$(find "${file_dir}" -name '**.yaml' -print | head -n 1)
            entity_kind=$(yq e '.kind' $catalog_file)
            entity_name=$(yq e '.metadata.name' $catalog_file)

            echo "Docs file: $f Dir: $file_dir Catalog file: $catalog_file Kind: $entity_kind Name: $entity_name"
            techdocs-cli generate --no-docker --source-dir ${file_dir}/ --output-dir ${file_dir}/site 
            techdocs-cli publish --publisher-type googleGcs --storage-name $TECHDOCS_S3_BUCKET_NAME --entity $ENTITY_NAMESPACE/$entity_kind/$entity_name --directory ${file_dir}/site 
          done
